### PR TITLE
Prevent directions from stacking up

### PR DESCRIPTION
**Pull request by mikocevar**
I've played around with the snake a bit and found a tiny bug. IF a user keep holding down a key, the direction commands will stack up and the next direction will be executed after all are released which produces lag.

### CODE REVIEW

**Comment by ChrisMorrisOrg** [comment]
Wow, so sorry I didn't respond sooner! I had noticed that bug but was using it as a cheat, but you're completely correct - if you can re-submit the change in the latest version, I can accept your PR... otherwise I'm happy to write the change and put a comment in the code attributing it to you :).

**Comment by degusssa** [comment]
Hi! No problem for the long reply!

I do not mind, if it's intended to works this way, feel free to have it like this. In my case it worked better, specially for mobile users.

You can implement the change or leave it as an option in your project. No need to attribute me, afterall it's a very minor fix :)

Thanks for asking though!

Best Regards, M.

**Comment by ChrisMorrisOrg** [comment]
Which reminds me, I should add in touch/swipe controls for modern smartphones. I attributed you anyway, since I think this is the first PR I've ever had submitted to me :P - 112bbe5d876f1b24125209b8618803d0a95407be

**Comment by degusssa** [comment]
Thank you!

**Pull request closed without merging**
